### ISSUE TITLE
Annotation XmlTransient

### ISSUE THREAD

**Issue by bracouda** [highsource/jaxb2-annotate-plugin#8]
Hello,
I have an object with an element who should be transient.
Exemple:
```
<xsd:complexType name="person" abstract="true">
        <xsd:sequence>
            <xsd:element name="id" type="xsd:int"></xsd:element>
            <xsd:element name="name" type="tns:media" minOccurs="0"></xsd:element>
        
            <xsd:element name="actif" type="xsd:boolean" minOccurs="1"></xsd:element>
            <xsd:element name="aliasList" type="tns:contactAlias" maxOccurs="unbounded" minOccurs="0">
            	<xsd:annotation>
            		<xsd:appinfo>
    					<annox:annotate target="field">@javax.xml.bind.annotation.XmlTransient</annox:annotate>
            		</xsd:appinfo>
            	</xsd:annotation>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
```

and in my java object i have 

```
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name="person", propOrder={"Id", "name", "atif", "aliasList"})
@XmlSeeAlso({personSingle.class})
public abstract class Contact implements Serializable
{
....
  @XmlTransient
  protected List<ContactAlias> aliasList;
```

The problem is aliasList still remain in propOrder. jaxb complains .
Do you know how i can fix it.

**Comment by nestaone** [comment]
Hello,
I'm facing exactly the same issue but I have'nt found any clean solution so far. So I'm also interrested in any clues!
Thx.

**Comment by nestaone** [comment]
The only workaround I found is to redefine @XmlType:

```xml
<jaxb:bindings node="//xs:complexType[@name='deviceType']" >
<annox:annotate target="class">
    <annox:annotate annox:class="javax.xml.bind.annotation.XmlType" name="deviceType"/>
</annox:annotate>

<annox:annotate target="class">
  <annox:annotate annox:class="javax.xml.bind.annotation.XmlType" propOrder="id 
   deviceName 
   type 
   manufacturer "/>
</annox:annotate>
 <jaxb:bindings node=".//xs:element[@name='deviceCatalog']" >              
       <annox:annotate target="field">@javax.xml.bind.annotation.XmlTransient</annox:annotate>
   </jaxb:bindings>	
 </jaxb:bindings>
```

**Comment by highsource** [comment]
@nestaone This is not a workaround, this is the correct solution.

@bracouda This is the correct behaviour. The `jaxb2-annotate-plugin` knows nothing about the semantics of the annotations. It just - and only - annotates. So if you instruct it to add `@XmlTransient` it does, as you order. And only that. So if you want `@XmlType.propOrder` to be changed as well, add the appropriate customization, it's up to you.

@nestaone By the way, I'd stick to Java syntax:

```xml
<annox:annotate target="class">
@javax.xml.bind.annotation.XmlType
(name="person", propOrder={"Id", "deviceName", "type", "manufacturer"})
</annox:annotate>
```

**Comment by brunolellis** [comment]
@highsource I have a question about annotating an atribute with `@XmlTransient`. Could you help me?

Using the same code as described in this issue, my attribute gets annotated with both `@XmlElement` and `@XmlTransient` (which is not allowed because they are mutually exclusive).

```
    @XmlElement(nillable = true)
    @XmlTransient
    protected XMLGregorianCalendar myDate;
```

What I need to do is to ignore "myDate" attribute. Any clues?
Thanks!

**Comment by highsource** [comment]
@brunolellis As I mentioned above, the plugin knows nothing about the semantics and constraints of annotations you add, so if you add `@XmlTransient`, nothing else (`@XmlElement`) etc. gets removed.

At the moment there is no functionality to remove an annotation. I can easily imagine something like:

```
 <annox:remove-annotation class="javax.xml.bind.XmlElement"/>
```

But it isn't there at the moment. Implementation would be quite simple, actually, but I don't know when I'll have resources to implement it. Open for PRs.

By the way, since you basically want to "ignore" certain properties, it may make sense to do that on the model level rather than on the code/annotations level. Check this answer on SO:

http://stackoverflow.com/questions/32560138/tell-jaxb-binding-compiler-which-elements-to-include

**Comment by brunolellis** [comment]
Thanks for your answer.

My xsd file describes an element like `<xs:element name="myDate" minOccurs="0" maxOccurs="1"	nillable="true" type="Entry:DateTime" />`. 
Because nillable is described, my element gets annotated with `@XmlElement(nillable = true)` and also serialized as `<myDate xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>`.

Maybe another solution is to just replace nillable using xjc. I don't even know if it is possible.

Anyway, thanks again for helping.

I will manage my time and try to help you with remove-annotation feature.
